### ISSUE TITLE
[Enhancement] window priority and overlap

### ISSUE THREAD

**Issue by leminsc8er** [ampersoftware/Creators.TF-Community-Launcher#13]
**UI or Mechanical Bug?**
UI Bug

**Describe the bug**
Can't handle Launcher Window if open Server Popup.

**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
no

**To Reproduce**
1. Go to list into Launcher Mainmenü on 'Creators.tf'
2. Click on 'Server-Button'
3. Click on  'Launcher-Window'
4. Can't show 'Launcher-Window' in front of 'Server-Window'

**Expected behavior**
Want handle Main-Launcher Windows without restricting the windows in front of it. i Want always open the server list and handle the launcher twice without closing server list

**Launcher Logs**
no need it

**Screenshots**
not need it

**Desktop**
 - Win 10
 - Launcher 0.1.0

**Additional context**
-

**Comment by rob5300** [comment]
This is expected behavior due to the server list window being a child of the main window. However we can look into changing this behavior.
What benefit is there for you to interact with the main window while the server list is also open?

**Comment by leminsc8er** [comment]
1. I am aware of that. I would like to switch the server list sometimes between different windows like tf2 or the browser ....
The launcher in the background, however, takes up a lot of field of view. In addition, it would be awesome if you could have launcher and server window for the taskbar groups even if they are dependent on each other.
2. I think looking ahead a little. As soon as new mods or settings are added, you might want to manage multiple windows simultaneously from the launcher.
what do you think?

**Comment by eisbaer66** [comment]
the serverlist is mod-dependend, isn't it? different mods show different servers, right?
maybe the serverlist could be an alternative view to where there are mod-links and a image shown right now (content-area)
- this would avoid the "having the launcher in background"-issue (since the launcher itself becomes the serverlist)
- but opening multiple serverlists for different mods would not be possible 
i think a unified serverlist containing all servers (of all mods) with good filters, sorting, etc. would be a better option, once multiple mods are supported

**Comment by leminsc8er** [comment]
here another example for windows 10.
1. i cant break the update window with "x"  or minimized it 
2. wile update i can't minimized the popup or the fullscree launcher window f.... this will breaks my workflow....
 https://i.imgur.com/8WcPrGI.png

**Comment by rob5300** [comment]
The last image is certainly an issue, probably due to how windows handles child windows.
It may not be solvable for now as a child window is desirable to prevent main window interaction during a download. Potentially we will change this UI to be integrated into the main window to solve this issue.
