### ISSUE TITLE
[Bug] Launcher Updater

### ISSUE THREAD

**Issue by leminsc8er** [ampersoftware/Creators.TF-Community-Launcher#16]
**UI or Mechanical Bug?**
mechanical
 
**Bug**
can't update via button from 0.1.11 to 0.1.2 (see screenshot)
online manual update via browser.

**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
yes

**Expected behavior**

**Launcher Logs**
https://pastebin.com/QdvQ8Vmb (2 weeks hosted)

**Screenshots**
https://imgur.com/a/EjhCW79

**Desktop (please complete the following information):**
 - OS: win10x64
 - Version 0.1.11

**Comment by jota11** [comment]
A bug fix is soon to follow. No reinstall will be needed, you will catch the newest version just fine with v0.1.11.

**Comment by jota11** [comment]
> A bug fix is soon to follow. No reinstall will be needed, you will catch the newest version just fine with v0.1.11.

The bug fix was released, v0.1.11 users can now catch the newest version without any problems. Please open another issue if you happen to have another problem.
