### ISSUE TITLE
[Enhancement] Profil Manager: Loadout

### ISSUE THREAD

**Issue by leminsc8er** [ampersoftware/Creators.TF-Community-Launcher#18]
**Is your feature request related to a problem? Please describe.**
Quick edit loadout without webside and change profiling.

**Is your feature request graphical or mechanical in nature?**
Graphical and mechanical.

**Describe the solution you'd like**
First Mockup for the loadout.
https://i.imgur.com/ABmZkj1.jpg _(not right view by exporting as image. mockups edit with https://app.diagrams.net/ . If you want i will send the editor file for this.)_

- disable or enable creators.tf loadout
- change profil for class
- task for profils
- show loadout by task
- overlfy button for window
- overfly-button for profils (_not on mockup_)
- some more...

**Would you like to work on this yourself, or leave it to the team and the community?**
team

**Extra Information**
-

**Comment by rob5300** [comment]
Website features will not be integrated into the launcher and we do not plan to.

**Comment by leminsc8er** [comment]
same for adding balancemod-servers into serverlist?
