### ISSUE TITLE
[Bug] TypeError : steamPaths is not iterable on a new installation.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ampersoftware/Creators.TF-Community-Launcher#22]
**UI or Mechanical Bug?**
A mechanical/operational bug, as it restrain me from fixing it by manually indicating the correct .steam path.
**Describe the bug**
On a new installation of Creators.TF launcher 0.1.30 on a GNU/Linux distribution (Solus), The launcher display this error message at launch, before closing if the message is closed, or validated.
**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
`TypeError : steamPaths is not iterable on a new installation`
**To Reproduce**
1. Place the 0.1.30 launcher files in /opt/creators-tf
2. Add execution permissions to creators-tf-launcher `sudo chmod +x /opt/creators-tf/creators-tf-launcher`
3. Execute it. `/opt/creators-tf/creators-tf-launcher`

**Expected behavior**
Either, notice the correct Steam installation folder `/home/pm/.steam/steam/` or Team Fortress 2 folder `/mnt/Ventilateur/SteamLibrary/steamapps/common/Team Fortress 2/` which is situated on an another hard-drive.
Or, Let me pass/ignore this error message, to allow me to change manually the paths manually into the launcher.

**Launcher Logs**
[main.log](https://github.com/ampersoftware/Creators.TF-Community-Launcher/files/5196409/main.log)
**Screenshots**
![image](https://user-images.githubusercontent.com/13170204/92621816-99703180-f2c4-11ea-8c9e-e1b68800827a.png)

**Desktop (please complete the following information):**
 - OS: Solus
```❯ neofetch
            -```````````                  pm@vix 
          `-+/------------.`              ------ 
       .---:mNo---------------.           OS: Solus 
     .-----yMMMy:---------------.         Kernel: 5.6.19-158.current 
   `------oMMMMMm/----------------`       Uptime: 5 hours, 12 mins 
  .------/MMMMMMMN+----------------.      Packages: 1206 (eopkg) 
 .------/NMMMMMMMMm-+/--------------.     Shell: bash 5.0.11 
`------/NMMMMMMMMMN-:mh/-------------`    Resolution: 3440x1440 
.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.    DE: Plasma 5.19.4 
-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--    WM: KWin 
----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.   WM Theme: Arc-OSX-White-Transparent 
.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`   Theme: WhiteSur [Plasma], WhiteSur-light [GTK2/3] 
`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.    Icons: Papirus-Light [Plasma], Papirus-Light [GTK2/3] 
`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+     Terminal: yakuake 
  .------------:://+-/++++++oshddys:      CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
   -hhhhyyyyyyyyyyyhhhhddddhysssso-       GPU: NVIDIA GeForce GTX 1060 6GB 
    `:ossssssyysssssssssssssssso:`        Memory: 13818MiB / 32043MiB (43%) 
      `:+ssssssssssssssssssss+-           GPU Driver: NVIDIA 450.66 
         `-/+ssssssssssso+/-`             Font: [Plasma], Noto Sans, 10 [GTK2/3] 
              `.-----..`                  Local IP:          .         .   .      
                                          Public IP:                :      :       
```
 - Version : 0.1.30

**Comment by win8linux** [comment]
Should be noted that this occurs with the program installed from the DEB package, too.

Specs:
```
OS: KDE neon User Edition 5.19 x86_64
Host: B450M DS3H
Kernel: 5.8.7-tkg-pds
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 5505MiB / 16020MiB
```

**Comment by rob5300** [comment]
was resoled by #25 and merged
