### ISSUE TITLE
[Enhancement] Let people start TF2 via the launcher

### ISSUE THREAD

**Issue by MeDerpWasTaken** [ampersoftware/Creators.TF-Community-Launcher#23]
**Is your feature request related to a problem? Please describe.**
No it is not

**Is your feature request graphical or mechanical in nature?**
Mechanical and Graphical?

**Describe the solution you'd like**
For a button to be added that lets you launch the game

**Would you like to work on this yourself, or leave it to the team and the community?**
Team and Community

**Extra Information**
The ability to set launch options should be included

**Comment by MeDerpWasTaken** [comment]
I guess you can join servers but it would be good idea anyway

**Comment by leminsc8er** [comment]
https://github.com/ampersoftware/Creators.TF-Community-Launcher/issues/3 same <3

**Comment by rob5300** [comment]
Will be added when the new quick play system is integrated.
