### ISSUE TITLE
[Enhancement] Use public repository to track mods instead of a json file

### ISSUE THREAD

**Issue by DanielMowitz** [ampersoftware/Creators.TF-Community-Launcher#24]
**Is your feature request related to a problem? Please describe.**
No.

**Is your feature request graphical or mechanical in nature?**
It is very much mechanical.

**Describe the solution you'd like**
I believe it would be a good idea to track the installable mods inside of a dedicated repository at `<something>.creators.tf`. It should contain files similar to the objects currently in mods.json, which would reside in a directory structure that would look something lke: `creators.tf mod repo -> mod -> verion -> mod.json`.

**Would you like to work on this yourself, or leave it to the team and the community?**
If I can be of any assistance I will do my best, but I believe this is mostly an organisatorial task.

**Extra Information**
Advantages of the proposed model:
  - No need to update the launcher to add/update mod listings
  - It's possible to create a more streamlined process for 3rd party modders to add mods
  - Allows for version control/updates

**Comment by rob5300** [comment]
We are considering changing this but currently due to the few additions in terms of mods its not a priority just yet. Will be done once things speed up.

**Comment by rob5300** [comment]
The main creators content will soon use a new system so this becomes less important.
I already plan to have a better system to allow new mods to be added without launcher updates so a change to "resolve" this will soon happen.

**Comment by rob5300** [comment]
This is now implemented!
