### ISSUE TITLE
leminsc8's first wishlist

### ISSUE THREAD

**Issue by leminsc8er** [ampersoftware/Creators.TF-Community-Launcher#3]
> _[future] = calls my idears in mind for the future_

**Launcher intern**
- auto-detect tf2 folder
- show launcher version
- add patreon donate link
     - add patreons like credits
- faq/info about launcher on start window
- tray icon 
     - quick options = versionsinfo; githublink; bugreport; ...
- tf2 start button
     - game autostart option after updates
     - start tf2 with own startscript.txt or window config =
     start fullscreen or something result; without intro; direct connect to server (specific options), exe autostartup for twitch.exe, external musicplayer.exe, discortd.exe, operaGX.exe://www.creators.tf; ...
     - quick conect to favorite creators server or maps
     - add favorite ip-server
     - [future] autoconnetct friends to same server =  contracker coop; ...
- [future]  import/export setting for launcher 
- [future]  import export content like mods and more
- rotate launcher wallpapers
- animated loading button with creators or tf2 symbol *([i will add animation source soon](https://))*
- auto update creators server files (new 1.8)

**Launcher tools**
- [future] creators-pack profiles - means own profiles for creators servers or other or testing and fun with individual acktiavate/deacitivate
- [future] creators.tf-updates-as-mod-pack - i think following mods must be integrated into tf2... > optimized for creators server! _(new 11.8)_
     -  more Icons like "Xonsistent Kill Icons" with new creators weapons
     - more crosshairs 
     - more animations = "paysus' Engineer First Person Animation Overhaul"; ...
     - new FX = "Toon Explosion FX; "Toon Muzzel Flashes"; Toon Righteous Bision FX"; "Toon Rocket Trails"; ...
- [future] hud-pack > optimized for creators server
- [future] sound-packs - with individual options > optimized for creators server
- [future] script-pack/editor  = taskskombo profil, contracker, serverlist, ... > optimized for creators server
- [future] fx-pack  = "Toon Explosion FX", ... > optimized for creators server
- [future] graphic-pack > optimized for creators server
- [future] frontline-meat-creators.tf-pack > optimized for creators server may as event not as mod?!
- [future] crosshair-pack > optimized for creators server _(new 11.8)_

   
  

**Changes**
- leave out "mod" by "uninstall mod"  button because their details on popup window

> i will permanently updated 👍 
> 
>- [x]  love creators.tf !
> 
>leminsc8

**Comment by leminsc8er** [comment]
now i will creat some new post for new wishes.
it will be better to handel the issues.
this list are the form i will post new issues in future.
please derive from this list.

**Comment by rob5300** [comment]
As these are suggestions and not an issue, this thread will be locked. May be re opened when such changes are made.
