### ISSUE TITLE
[Bug] Launcher crashing when the progress bar is complete

### ISSUE THREAD

**Issue by asdsdsaaad** [ampersoftware/Creators.TF-Community-Launcher#31]
**UI or Mechanical Bug?**
Is this a user Interface bug or a mechanical/operational bug?
Mechanical.
**Describe the bug**
When installing creators.tf and the progress bar is full,the launcher crashes without reason.
**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
[Error dialog if applicable]

**To Reproduce**

**Expected behavior**
For the game to install.
**Launcher Logs**
Please upload the logs from your launcher either here, or on a site such as pastebin.
You can find the logs in the "logs" folder in the "Config/Log Folder". Use the button in the Settings menu in launcher to find the folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/75376158/100883686-6090c480-348f-11eb-9252-bbc477f1b66b.png)

**Desktop (please complete the following information):**
Windows 7 
Service Pack 1
**Additional context**

**Comment by rob5300** [comment]
I will try to look into this in the coming days

**Comment by asdsdsaaad** [comment]
I have got a new error after updating the launcher,here it is. 
![image](https://user-images.githubusercontent.com/75376158/104520481-f87ae580-55d9-11eb-9768-6b0a42034bcf.png)
