### ISSUE TITLE
[Bug] I have some problem with 18th century gifting lantern I've collected 472 points, but I can't fill the score after that. What should I do?

### ISSUE THREAD

**Issue by meemjic** [ampersoftware/Creators.TF-Community-Launcher#36]
**UI or Mechanical Bug?**
Is this a user Interface bug or a mechanical/operational bug?

**Describe the bug**

**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
[Error dialog if applicable]

**To Reproduce**

**Expected behavior**

**Launcher Logs**
Please upload the logs from your launcher either here, or on a site such as pastebin.
You can find the logs in the "logs" folder in the "Config/Log Folder". Use the button in the Settings menu in launcher to find the folder.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rob5300** [comment]
This is not the place to report bugs for creators.tf server content. Launcher bugs only.
You need to report this properly on our discord server: [](https://creators.tf/discord)
