### ISSUE TITLE
[Bug] Zip extraction errors in a fresh install of TF2

### ISSUE THREAD

**Issue by mhetralla** [ampersoftware/Creators.TF-Community-Launcher#45]
**UI or Mechanical Bug?**
Mechanical bug

**Describe the bug**
The launcher (0.2.3) fails to extract some files from the zip if TF2 has not been launched for the first time. It show hundreds of error dialogues, one after the other. The extraction keeps happening in the background.

**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
Mod Install Error : Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\download\materials\models\bots\demo\demo_bot_redo.vmt'.
Error Stack:Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\download\materials\models\bots\demo\demo_bot_redo.vmt'

**To Reproduce**
1. Download TF2 from Steam, but don't launch it
2. Download and install the Launcher
3. Download the Creators.tf pack from the Launcher
4. The program finishes downloading and start exctracting the zip, and the error dialogues are shown

**Expected behavior**
After the download, the zip gets extracted without errors.

**Launcher Logs**
main.log
https://a.pomf.cat/zjyjgd.log

**Desktop:**
 - OS: Windows
 - Version 7

**Comment by rob5300** [comment]
Will look into this, some others have also reported it
