### ISSUE TITLE
[Enhancement] Support new website features

### ISSUE THREAD

**Issue by Tank-Missile** [ampersoftware/Creators.TF-Community-Launcher#48]
**Is your feature request related to a problem? Please describe.**
The creators.tf website updated to split matchmaking, Mann VS. Machine, and the server browser into their own sections. The launcher does not feature a way to use matchmaking, and the MVM and casual servers are squashed together in the same list. At the very least providing a way to filter servers based on gamemode (mvm, casual, payload, 5cp, etc) would be a nice quality of life change.

**Is your feature request graphical or mechanical in nature?**
Graphical

**Describe the solution you'd like**
Add 2 extra tabs to the sidebar: Matchmaking and Mann VS. Machine. Keep MVM servers out of the casual server list.

**Would you like to work on this yourself, or leave it to the team and the community?**
If the developers of this launcher are not willing to add these features, I could give a crack at it. I'm not very experienced with Node.JS, but I do know how to code in JavaScript.

**Comment by BernardoGomesNegri** [comment]
If you tried to make it yourself, you would probably have to wait until Digital Directive is over, because Quickplay is disabled at the moment, and thus, only the developers know how to communicate with their back-end api.

**Comment by Tank-Missile** [comment]
Interesting... I had a bookmark saved to the quickplay page, but the Find a Server button no longer leads there. I guess it's still under development. In that case, separating the different server gamemodes into tabs would suffice, or have a filter that does the same job.

**Comment by BernardoGomesNegri** [comment]
They temporarily disabled the quickplay page until the current event is over. If you try to manually send the request to their servers, it says that quickplay is temporarily disabled.

**Comment by Tank-Missile** [comment]
I understand that now, but let me reiterate: Could filters/tabs for different gamemodes be added? Currently all Creators.TF servers are squashed into a single list.

**Comment by BernardoGomesNegri** [comment]
I am not a developer, so I do not know what is in their plans.
